// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEcwyxa_zmvAEjaUY7iyftZSGgLD4iXDI',
    appId: '1:354553502428:android:6404d8f83c786b1c2eb219',
    messagingSenderId: '354553502428',
    projectId: 'ammoagilocano-6bbfd',
    storageBucket: 'ammoagilocano-6bbfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkpJQzPE7Vl7uRfHu0VymRBYerexL_Ntw',
    appId: '1:354553502428:ios:c7fc48cf98d275432eb219',
    messagingSenderId: '354553502428',
    projectId: 'ammoagilocano-6bbfd',
    storageBucket: 'ammoagilocano-6bbfd.appspot.com',
    androidClientId: '354553502428-cdkgtmhj1f2482gpp1kt88urlirkti2m.apps.googleusercontent.com',
    iosClientId: '354553502428-ekgu4120vu28pmv02i8l9juac4uhaach.apps.googleusercontent.com',
    iosBundleId: 'com.example.aagilocano1',
  );

}